language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
  - fix_travis
script:
- webdriver-manager update --standalone false --gecko false --versions.chrome 2.35
- ng e2e --protractor-config ./e2e/protractor.conf.headless.js --webdriver-update=false
- ng lint
- ng test --watch=false --progress=false --browsers ChromeHeadlessNoSandbox
- ng build --prod --base-href https://rolandfuchsberger.github.io/balanced-braces/
