language: node_js
node_js:
  - "9"
dist: trusty
sudo: required
branches:
  only:
  - master
  - deploy_travis

jobs:
  include:
    - stage: test
      script:
      - ng lint
    - 
      script:
      - ng test --watch=false --progress=false --browsers ChromeHeadlessNoSandbox
    -
      script:
      - echo 'installing webdriver that works with chrome version 62.0 - which is installed on Travis node_js 9 image'
      - webdriver-manager update --standalone false --gecko false --versions.chrome 2.35
      - ng e2e --protractor-config ./e2e/protractor.conf.headless.js --webdriver-update=false
    -
      script:
      - echo 'test-build'
      - ng build --prod
    - stage: deploy
      script:
      - ng build --prod --base-href https://rolandfuchsberger.github.io/balanced-braces/
      deploy:
        provider: pages
        skip_cleanup: true
        github_token: $GITHUB_TOKEN
        local_dir: dist/balanced-braces
        on:
          all_branches: true
